# Generated by Django 3.1.3 on 2021-09-07 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('first_lastname', models.CharField(max_length=50, verbose_name='first lastname')),
                ('second_lastname', models.CharField(max_length=50, verbose_name='second lastname')),
                ('street', models.CharField(max_length=80, verbose_name='street')),
                ('number', models.CharField(max_length=10, verbose_name='number')),
                ('suburb', models.CharField(max_length=80, verbose_name='suburb')),
                ('zip_code', models.CharField(max_length=10, verbose_name='zip code')),
                ('phone', models.CharField(max_length=15, verbose_name='phone')),
                ('rfc', models.CharField(max_length=12, verbose_name='rfc')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Sent'), (1, 'Authorized'), (2, 'Rejected')], default=0, verbose_name='status')),
            ],
            options={
                'verbose_name': 'prospect',
                'verbose_name_plural': 'prospects',
                'default_related_name': 'prospects',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('file', models.FileField(upload_to='documents/', verbose_name='document')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='prospects.prospects')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'default_related_name': 'documents',
            },
        ),
    ]
