# Generated by Django 3.1.3 on 2021-09-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0002_auto_20210907_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prospects',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prospects',
            name='rfc',
            field=models.CharField(max_length=13, verbose_name='rfc'),
        ),
    ]
