# Generated by Django 3.1.3 on 2021-09-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0003_auto_20210908_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospects',
            name='reject_details',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='reject details'),
        ),
    ]
